### PR TITLE
Update gradle

### PR DESCRIPTION
**Pull request by timonback**
Align version with springwolf-core

### CODE REVIEW

**Comment by stavshamir** [comment]
I tried upgrading gradle a few month ago. The publish to maven plugin did not work in gradle 6 or 7 and there was no informative error (more specifically, something in the way the plugin created the release has changed, and sonatype rejected the release).

**Comment by timonback** [comment]
springwolf-core is using the same gradle version.

Is that specific to the custom gradle publication task?
If so, I might attempt to build snapshots on this feature branch till I get something working

**Comment by stavshamir** [comment]
It's relate either to the `maven-publish` or to the `signing` gradle plugins (I suspect the later). Unfortunately there is little documentation, and gradle notoriously breaks stuff when they upgrade.
Trying with the snapshots is a good idea. We actually must upgrade gradle so we will be able to upgrade spring version, so this is an important task.

**Comment by timonback** [comment]
I just pushed code to test the publishing. It seems that the secrets are not set on PR (from a fork) - which is a good thing in terms of security.

Unfortunately, I am not able to assist finding the issue here.

**Comment by stavshamir** [comment]
Thanks for trying, will we try to make it work in the next release. I am seriously considering moving to maven which has much better documentation, especially for this plugin

**Comment by stavshamir** [comment]
I figured it out in another PR, closing this

**Pull request closed without merging**
